<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Advanced Search</name>
   <tag></tag>
   <elementGuidId>9de23b42-c008-4990-bd54-ab2bcab96f40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[@class='panel-controls'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.panel-control-collapse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4f53661e-f5fd-4547-904d-1f9fa4d91936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-control-collapse</value>
      <webElementGuid>4cd3c1f6-0fcd-4841-8958-d412247f6d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-dashboard[1]/div[@class=&quot;content_wrapper&quot;]/app-pricing-booking-search[1]/app-collapsible-panel[@class=&quot;advanced-search&quot;]/div[@class=&quot;collapsible-panel panel panel-visible  panel-collapsed&quot;]/div[@class=&quot;panel-heading heading-search heading-table&quot;]/span[@class=&quot;panel-controls&quot;]/a[@class=&quot;panel-control-collapse&quot;]</value>
      <webElementGuid>e2b7f828-eb78-4a43-9d21-327dde78a859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-dashboard/div/app-pricing-booking-search/app-collapsible-panel/div/div/span/a[2]</value>
      <webElementGuid>6a7a3e86-15bb-4d86-bdf2-989e4f7bc5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>342f95c7-cc16-4d21-9d78-27763aa1346f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
