<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button Advanced Search</name>
   <tag></tag>
   <elementGuidId>9de23b42-c008-4990-bd54-ab2bcab96f40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-dashboard//app-pricing-booking-search//div[contains(@class, 'heading-search')]//a[@class= 'panel-control-collapse']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.panel-control-collapse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed57ac42-b15e-4702-bd9b-f0c02cd20171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel-control-collapse</value>
      <webElementGuid>858eca07-87cf-4c74-89a9-2bde6f7cc836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)/app-corp[1]/app-dashboard[1]/div[@class=&quot;content_wrapper&quot;]/app-pricing-booking-search[1]/app-collapsible-panel[@class=&quot;advanced-search&quot;]/div[@class=&quot;collapsible-panel panel panel-visible  panel-collapsed&quot;]/div[@class=&quot;panel-heading heading-search heading-table&quot;]/span[@class=&quot;panel-controls&quot;]/a[@class=&quot;panel-control-collapse&quot;]</value>
      <webElementGuid>d504a572-0dcf-4b37-8949-e29e83282f37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='corp']/app-corp/app-dashboard/div/app-pricing-booking-search/app-collapsible-panel/div/div/span/a[2]</value>
      <webElementGuid>187e5bbd-097d-460a-96f0-8248c1124ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>5bf4ac2d-9aa0-458e-9982-32dfec1369bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
