<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>first Cell in Dashboard Orders</name>
   <tag></tag>
   <elementGuidId>657c8310-5fa2-4c37-bc00-cb7440fe49ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-collapsible-panel//table/tbody/tr[1]/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>76f78c02-867f-4c6b-acce-d8bfb4bb6c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>F/APHAR1030</value>
      <webElementGuid>fe2eebd5-98db-4378-93c8-7d6bb421aa09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_4&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[1]</value>
      <webElementGuid>3aa7b1a8-8343-47be-8f0b-de50d4a47a15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_4']/tbody/tr/td</value>
      <webElementGuid>5c2cd417-c2bf-44a2-bce0-e785c1c05b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Track &amp; Trace'])[2]/following::td[1]</value>
      <webElementGuid>02a5d0d7-d1b4-4ef0-b152-e44ec5115de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Motif'])[2]/following::td[1]</value>
      <webElementGuid>99034a7e-aaff-47d3-ae9c-e58ed8bbddcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EDWARDS LIFESCIENCES'])[1]/preceding::td[2]</value>
      <webElementGuid>ce248baf-c282-44e3-9715-1a46c8afe333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHUM PZQ LIVRAISON LA MEYNARDE'])[1]/preceding::td[3]</value>
      <webElementGuid>54974ce8-b773-413c-b8f2-3daafb7946ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='F/APHAR1030']/parent::*</value>
      <webElementGuid>4f4b9254-c301-4343-9d50-d4c1884d8486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>cbb1c6cf-6fbe-4edb-8b94-2140e0da1fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'F/APHAR1030' or . = 'F/APHAR1030')]</value>
      <webElementGuid>1c1fc476-4c94-4781-8db8-1b1634be3ec8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
